export interface SkillItem {
  name: string;
  domain: "Frontend" | "Backend" | "DevOps" | "Mobile" | "QA" | "Design";
}

export const SKILLS_CATALOG: SkillItem[] = [
  // Frontend
  { name: "JavaScript", domain: "Frontend" },
  { name: "TypeScript", domain: "Frontend" },
  { name: "React", domain: "Frontend" },
  { name: "Next.js", domain: "Frontend" },
  { name: "Vue.js", domain: "Frontend" },
  { name: "Nuxt.js", domain: "Frontend" },
  { name: "Angular", domain: "Frontend" },
  { name: "Svelte", domain: "Frontend" },
  { name: "HTML5", domain: "Frontend" },
  { name: "CSS3", domain: "Frontend" },
  { name: "Tailwind CSS", domain: "Frontend" },
  { name: "Redux", domain: "Frontend" },
  { name: "Zustand", domain: "Frontend" },
  { name: "TanStack Query", domain: "Frontend" },
  { name: "Webpack", domain: "Frontend" },
  { name: "Vite", domain: "Frontend" },
  { name: "WebSockets", domain: "Frontend" },
  { name: "GraphQL", domain: "Frontend" },
  { name: "Responsive Design", domain: "Frontend" },
  { name: "Web Performance", domain: "Frontend" },

  // Backend
  { name: "Node.js", domain: "Backend" },
  { name: "Express.js", domain: "Backend" },
  { name: "NestJS", domain: "Backend" },
  { name: "Python", domain: "Backend" },
  { name: "Django", domain: "Backend" },
  { name: "FastAPI", domain: "Backend" },
  { name: "Go (Golang)", domain: "Backend" },
  { name: "Java", domain: "Backend" },
  { name: "Spring Boot", domain: "Backend" },
  { name: "C# / .NET", domain: "Backend" },
  { name: "Ruby on Rails", domain: "Backend" },
  { name: "PHP", domain: "Backend" },
  { name: "Laravel", domain: "Backend" },
  { name: "PostgreSQL", domain: "Backend" },
  { name: "MySQL", domain: "Backend" },
  { name: "MongoDB", domain: "Backend" },
  { name: "Redis", domain: "Backend" },
  { name: "Prisma ORM", domain: "Backend" },
  { name: "TypeORM", domain: "Backend" },
  { name: "REST APIs", domain: "Backend" },
  { name: "gRPC", domain: "Backend" },
  { name: "Kafka", domain: "Backend" },
  { name: "RabbitMQ", domain: "Backend" },
  { name: "Microservices", domain: "Backend" },

  // DevOps & Cloud
  { name: "Docker", domain: "DevOps" },
  { name: "Kubernetes", domain: "DevOps" },
  { name: "AWS", domain: "DevOps" },
  { name: "Google Cloud (GCP)", domain: "DevOps" },
  { name: "Microsoft Azure", domain: "DevOps" },
  { name: "Terraform", domain: "DevOps" },
  { name: "Ansible", domain: "DevOps" },
  { name: "CI/CD", domain: "DevOps" },
  { name: "GitHub Actions", domain: "DevOps" },
  { name: "GitLab CI", domain: "DevOps" },
  { name: "Linux", domain: "DevOps" },
  { name: "Nginx", domain: "DevOps" },
  { name: "Prometheus", domain: "DevOps" },
  { name: "Grafana", domain: "DevOps" },

  // Mobile
  { name: "React Native", domain: "Mobile" },
  { name: "Flutter", domain: "Mobile" },
  { name: "Swift", domain: "Mobile" },
  { name: "SwiftUI", domain: "Mobile" },
  { name: "Kotlin", domain: "Mobile" },
  { name: "Android Jetpack Compose", domain: "Mobile" },
  { name: "iOS SDK", domain: "Mobile" },
  { name: "Dart", domain: "Mobile" },

  // QA & Testing
  { name: "Jest", domain: "QA" },
  { name: "Vitest", domain: "QA" },
  { name: "Playwright", domain: "QA" },
  { name: "Cypress", domain: "QA" },
  { name: "Selenium", domain: "QA" },
  { name: "Unit Testing", domain: "QA" },
  { name: "E2E Testing", domain: "QA" },
  { name: "Integration Testing", domain: "QA" },

  // Design
  { name: "Figma", domain: "Design" },
  { name: "UI/UX Design", domain: "Design" },
  { name: "Design Systems", domain: "Design" },
  { name: "Wireframing", domain: "Design" },
  { name: "Prototyping", domain: "Design" },
  { name: "Adobe XD", domain: "Design" },
];

/** Curated fallback skills dictionary based on common keywords in title */
export const DEFAULT_ROLE_SKILLS: Record<string, string[]> = {
  frontend: [
    "React",
    "TypeScript",
    "Next.js",
    "Tailwind CSS",
    "HTML5",
    "CSS3",
    "REST APIs",
    "Jest",
  ],
  backend: [
    "Node.js",
    "TypeScript",
    "PostgreSQL",
    "REST APIs",
    "Docker",
    "Redis",
    "Microservices",
  ],
  fullstack: [
    "React",
    "TypeScript",
    "Next.js",
    "Node.js",
    "PostgreSQL",
    "Tailwind CSS",
    "Docker",
    "REST APIs",
  ],
  devops: [
    "Docker",
    "Kubernetes",
    "AWS",
    "CI/CD",
    "Terraform",
    "Linux",
    "GitHub Actions",
    "Prometheus",
  ],
  mobile: [
    "React Native",
    "Flutter",
    "TypeScript",
    "iOS SDK",
    "Kotlin",
    "Swift",
    "REST APIs",
  ],
  qa: [
    "Playwright",
    "Cypress",
    "Jest",
    "E2E Testing",
    "Unit Testing",
    "CI/CD",
    "TypeScript",
  ],
  design: [
    "Figma",
    "UI/UX Design",
    "Design Systems",
    "Wireframing",
    "Prototyping",
    "Responsive Design",
  ],
};
